packages:
  - packages/*
  - '!playgrounds'

patchedDependencies:
  '@vue.ts/complex-types': patches/@vue.ts__complex-types.patch

catalogs:
  build:
    '@antfu/eslint-config': ^4.16.2
    '@googlemaps/js-api-loader': ^1.16.10
    '@vitejs/plugin-vue': ^6.0.0
    '@vue.ts/complex-types': ^0.6.0
    bumpp: ^10.2.0
    consola: ^3.4.2
    eslint: ^9.30.1
    esno: ^4.8.0
    lint-staged: ^16.1.2
    npm-run-all2: ^8.0.4
    pnpm: ^10.13.1
    rimraf: ^6.0.1
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsdown: ^0.12.9
    typescript: ^5.8.3
    unplugin-vue: ^6.2.0
    vite: npm:rolldown-vite@latest
    vue: ^3.5.17
    vue-component-type-helpers: &volar ^3.0.1
    vue-tsc: *volar

  deps:
    '@vueuse/core': &vueuse ^13.5.0
    '@vueuse/shared': *vueuse

  docs:
    unocss: &unocss ^66.3.3
    '@unocss/eslint-plugin': *unocss
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.6.1
    vitepress-plugin-llms: ^1.7.0

  types:
    '@types/google.maps': ^3.58.1
    '@types/node': ^24.0.13

onlyBuiltDependencies:
  - pnpm
  - esno
  - rolldown
  - simple-git-hooks
