packages:
  - packages/*
  - '!playgrounds'
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@antfu/ni': ^23.2.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^20.17.14
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^9.10.1
  consola: ^3.4.0
  eslint: ^9.18.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fs-extra: ^11.3.0
  lint-staged: ^15.4.1
  pnpm: ^9.15.4
  rimraf: ^5.0.10
  simple-git-hooks: ^2.11.1
  taze: ^18.2.0
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vite: ^6.0.7
  vite-plugin-dts: ^4.5.0
  vite-plugin-replace: ^0.1.1
  vite-plugin-style-inject: ^0.0.1
  vitepress: 1.0.0-beta.7
  vue: ^3.5.13
  '@vue/tsconfig': ^0.7.0
  '@googlemaps/js-api-loader': ^1.16.8
  '@types/google.maps': ^3.58.1
  vue-component-type-helpers: ^2.2.0
