packages:
  - packages/*
  - '!playgrounds'

patchedDependencies:
  '@vue.ts/complex-types': patches/@vue.ts__complex-types.patch

catalogs:
  build:
    '@googlemaps/js-api-loader': ^1.16.8
    '@vitejs/plugin-vue': ^5.2.3
    '@vue.ts/complex-types': ^0.6.0
    '@vueuse/core': ^13.0.0
    '@vueuse/shared': ^13.0.0
    tsdown: ^0.12.7
    unplugin-vue: ^6.2.0
    vite: npm:rolldown-vite@latest
    vue: ^3.5.13
    vue-component-type-helpers: ^2.2.0

  dev:
    '@antfu/eslint-config': ^4.11.0
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    eslint: ^9.23.0
    esno: ^4.8.0
    lint-staged: ^15.5.0
    pnpm: ^10.7.1
    rimraf: ^6.0.1
    simple-git-hooks: ^2.12.1
    taze: ^18.5.0
    typescript: ^5.8.2
    vue-tsc: ^2.2.8

  docs:
    '@unocss/eslint-plugin': ^66.2.3
    unocss: ^66.2.3
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.6.0
    vitepress-plugin-llms: ^1.5.1

  types:
    '@types/google.maps': ^3.58.1
    '@types/node': ^24.0.1

onlyBuiltDependencies:
  - pnpm
  - esno
  - simple-git-hooks
